[theme]
primaryColor = "#003398"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1a1a"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[server]
headless = true
port = 8501
